{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "f26582a2-54fa-4ac1-9777-9c2ac25a6d5a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting firebase-admin\n",
      "  Downloading firebase_admin-7.1.0-py3-none-any.whl.metadata (1.7 kB)\n",
      "Collecting cachecontrol>=0.14.3 (from firebase-admin)\n",
      "  Downloading cachecontrol-0.14.4-py3-none-any.whl.metadata (3.1 kB)\n",
      "Collecting google-api-core<3.0.0dev,>=2.25.1 (from google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin)\n",
      "  Downloading google_api_core-2.28.1-py3-none-any.whl.metadata (3.3 kB)\n",
      "Collecting google-cloud-firestore>=2.21.0 (from firebase-admin)\n",
      "  Downloading google_cloud_firestore-2.21.0-py3-none-any.whl.metadata (9.9 kB)\n",
      "Collecting google-cloud-storage>=3.1.1 (from firebase-admin)\n",
      "  Downloading google_cloud_storage-3.7.0-py3-none-any.whl.metadata (14 kB)\n",
      "Requirement already satisfied: pyjwt>=2.10.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pyjwt[crypto]>=2.10.1->firebase-admin) (2.10.1)\n",
      "Requirement already satisfied: httpx==0.28.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx[http2]==0.28.1->firebase-admin) (0.28.1)\n",
      "Requirement already satisfied: anyio in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase-admin) (4.7.0)\n",
      "Requirement already satisfied: certifi in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase-admin) (2025.10.5)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase-admin) (1.0.9)\n",
      "Requirement already satisfied: idna in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase-admin) (3.7)\n",
      "Collecting h2<5,>=3 (from httpx[http2]==0.28.1->firebase-admin)\n",
      "  Downloading h2-4.3.0-py3-none-any.whl.metadata (5.1 kB)\n",
      "Collecting googleapis-common-protos<2.0.0,>=1.56.2 (from google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin)\n",
      "  Downloading googleapis_common_protos-1.72.0-py3-none-any.whl.metadata (9.4 kB)\n",
      "Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin) (5.29.3)\n",
      "Collecting proto-plus<2.0.0,>=1.22.3 (from google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin)\n",
      "  Downloading proto_plus-1.26.1-py3-none-any.whl.metadata (2.2 kB)\n",
      "Collecting google-auth<3.0.0,>=2.14.1 (from google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin)\n",
      "  Downloading google_auth-2.43.0-py2.py3-none-any.whl.metadata (6.6 kB)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.18.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin) (2.32.3)\n",
      "Collecting grpcio<2.0.0,>=1.33.2 (from google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin)\n",
      "  Downloading grpcio-1.76.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)\n",
      "Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin)\n",
      "  Downloading grpcio_status-1.76.0-py3-none-any.whl.metadata (1.1 kB)\n",
      "Requirement already satisfied: cachetools<7.0,>=2.0.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin) (5.5.1)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin) (0.2.8)\n",
      "Collecting rsa<5,>=3.1.4 (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin)\n",
      "  Downloading rsa-4.9.1-py3-none-any.whl.metadata (5.6 kB)\n",
      "Requirement already satisfied: typing-extensions~=4.12 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin) (4.12.2)\n",
      "Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 (from google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin)\n",
      "  Downloading protobuf-6.33.2-cp310-abi3-win_amd64.whl.metadata (593 bytes)\n",
      "Collecting hyperframe<7,>=6.1 (from h2<5,>=3->httpx[http2]==0.28.1->firebase-admin)\n",
      "  Downloading hyperframe-6.1.0-py3-none-any.whl.metadata (4.3 kB)\n",
      "Collecting hpack<5,>=4.1 (from h2<5,>=3->httpx[http2]==0.28.1->firebase-admin)\n",
      "  Downloading hpack-4.1.0-py3-none-any.whl.metadata (4.6 kB)\n",
      "Requirement already satisfied: h11>=0.16 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx==0.28.1->httpx[http2]==0.28.1->firebase-admin) (0.16.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin) (3.3.2)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin) (2.3.0)\n",
      "Requirement already satisfied: pyasn1>=0.1.3 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from rsa<5,>=3.1.4->google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != \"PyPy\"->firebase-admin) (0.4.8)\n",
      "Requirement already satisfied: msgpack<2.0.0,>=0.5.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from cachecontrol>=0.14.3->firebase-admin) (1.0.3)\n",
      "Collecting google-cloud-core<3.0.0,>=1.4.1 (from google-cloud-firestore>=2.21.0->firebase-admin)\n",
      "  Downloading google_cloud_core-2.5.0-py3-none-any.whl.metadata (3.1 kB)\n",
      "Collecting google-resumable-media<3.0.0,>=2.7.2 (from google-cloud-storage>=3.1.1->firebase-admin)\n",
      "  Downloading google_resumable_media-2.8.0-py3-none-any.whl.metadata (2.6 kB)\n",
      "Collecting google-crc32c<2.0.0,>=1.1.3 (from google-cloud-storage>=3.1.1->firebase-admin)\n",
      "  Downloading google_crc32c-1.7.1-cp313-cp313-win_amd64.whl.metadata (2.4 kB)\n",
      "Requirement already satisfied: cryptography>=3.4.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pyjwt[crypto]>=2.10.1->firebase-admin) (44.0.1)\n",
      "Requirement already satisfied: cffi>=1.12 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->firebase-admin) (1.17.1)\n",
      "Requirement already satisfied: pycparser in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->firebase-admin) (2.21)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from anyio->httpx==0.28.1->httpx[http2]==0.28.1->firebase-admin) (1.3.0)\n",
      "Downloading firebase_admin-7.1.0-py3-none-any.whl (137 kB)\n",
      "Downloading google_api_core-2.28.1-py3-none-any.whl (173 kB)\n",
      "Downloading google_auth-2.43.0-py2.py3-none-any.whl (223 kB)\n",
      "Downloading googleapis_common_protos-1.72.0-py3-none-any.whl (297 kB)\n",
      "Downloading grpcio-1.76.0-cp313-cp313-win_amd64.whl (4.7 MB)\n",
      "   ---------------------------------------- 0.0/4.7 MB ? eta -:--:--\n",
      "   ---------------------- ----------------- 2.6/4.7 MB 13.5 MB/s eta 0:00:01\n",
      "   ------------------------------- -------- 3.7/4.7 MB 8.0 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 4.7/4.7 MB 8.2 MB/s eta 0:00:00\n",
      "Downloading grpcio_status-1.76.0-py3-none-any.whl (14 kB)\n",
      "Downloading h2-4.3.0-py3-none-any.whl (61 kB)\n",
      "Downloading hpack-4.1.0-py3-none-any.whl (34 kB)\n",
      "Downloading hyperframe-6.1.0-py3-none-any.whl (13 kB)\n",
      "Downloading proto_plus-1.26.1-py3-none-any.whl (50 kB)\n",
      "Downloading protobuf-6.33.2-cp310-abi3-win_amd64.whl (436 kB)\n",
      "Downloading rsa-4.9.1-py3-none-any.whl (34 kB)\n",
      "Downloading cachecontrol-0.14.4-py3-none-any.whl (22 kB)\n",
      "Downloading google_cloud_firestore-2.21.0-py3-none-any.whl (368 kB)\n",
      "Downloading google_cloud_core-2.5.0-py3-none-any.whl (29 kB)\n",
      "Downloading google_cloud_storage-3.7.0-py3-none-any.whl (303 kB)\n",
      "Downloading google_crc32c-1.7.1-cp313-cp313-win_amd64.whl (33 kB)\n",
      "Downloading google_resumable_media-2.8.0-py3-none-any.whl (81 kB)\n",
      "Installing collected packages: rsa, protobuf, hyperframe, hpack, grpcio, google-crc32c, proto-plus, h2, googleapis-common-protos, google-resumable-media, google-auth, cachecontrol, grpcio-status, google-api-core, google-cloud-core, google-cloud-storage, google-cloud-firestore, firebase-admin\n",
      "\n",
      "   ----------------------------------------  0/18 [rsa]\n",
      "   ----------------------------------------  0/18 [rsa]\n",
      "   ----------------------------------------  0/18 [rsa]\n",
      "   ----------------------------------------  0/18 [rsa]\n",
      "  Attempting uninstall: protobuf\n",
      "   ----------------------------------------  0/18 [rsa]\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "    Found existing installation: protobuf 5.29.3\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "    Uninstalling protobuf-5.29.3:\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "      Successfully uninstalled protobuf-5.29.3\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "   -- -------------------------------------  1/18 [protobuf]\n",
      "   ------ ---------------------------------  3/18 [hpack]\n",
      "   ------ ---------------------------------  3/18 [hpack]\n",
      "   -------- -------------------------------  4/18 [grpcio]\n",
      "   -------- -------------------------------  4/18 [grpcio]\n",
      "   -------- -------------------------------  4/18 [grpcio]\n",
      "   -------- -------------------------------  4/18 [grpcio]\n",
      "   -------- -------------------------------  4/18 [grpcio]\n",
      "   -------- -------------------------------  4/18 [grpcio]\n",
      "   -------- -------------------------------  4/18 [grpcio]\n",
      "   ----------- ----------------------------  5/18 [google-crc32c]\n",
      "   ------------- --------------------------  6/18 [proto-plus]\n",
      "   ------------- --------------------------  6/18 [proto-plus]\n",
      "   --------------- ------------------------  7/18 [h2]\n",
      "   ----------------- ----------------------  8/18 [googleapis-common-protos]\n",
      "   ----------------- ----------------------  8/18 [googleapis-common-protos]\n",
      "   ----------------- ----------------------  8/18 [googleapis-common-protos]\n",
      "   ----------------- ----------------------  8/18 [googleapis-common-protos]\n",
      "   ----------------- ----------------------  8/18 [googleapis-common-protos]\n",
      "   ----------------- ----------------------  8/18 [googleapis-common-protos]\n",
      "   -------------------- -------------------  9/18 [google-resumable-media]\n",
      "   ---------------------- ----------------- 10/18 [google-auth]\n",
      "   ---------------------- ----------------- 10/18 [google-auth]\n",
      "   ---------------------- ----------------- 10/18 [google-auth]\n",
      "   ---------------------- ----------------- 10/18 [google-auth]\n",
      "   ---------------------- ----------------- 10/18 [google-auth]\n",
      "   ------------------------ --------------- 11/18 [cachecontrol]\n",
      "   -------------------------- ------------- 12/18 [grpcio-status]\n",
      "   ---------------------------- ----------- 13/18 [google-api-core]\n",
      "   ---------------------------- ----------- 13/18 [google-api-core]\n",
      "   ---------------------------- ----------- 13/18 [google-api-core]\n",
      "   ---------------------------- ----------- 13/18 [google-api-core]\n",
      "   ------------------------------- -------- 14/18 [google-cloud-core]\n",
      "   --------------------------------- ------ 15/18 [google-cloud-storage]\n",
      "   --------------------------------- ------ 15/18 [google-cloud-storage]\n",
      "   --------------------------------- ------ 15/18 [google-cloud-storage]\n",
      "   --------------------------------- ------ 15/18 [google-cloud-storage]\n",
      "   --------------------------------- ------ 15/18 [google-cloud-storage]\n",
      "   ----------------------------------- ---- 16/18 [google-cloud-firestore]\n",
      "   ----------------------------------- ---- 16/18 [google-cloud-firestore]\n",
      "   ----------------------------------- ---- 16/18 [google-cloud-firestore]\n",
      "   ----------------------------------- ---- 16/18 [google-cloud-firestore]\n",
      "   ----------------------------------- ---- 16/18 [google-cloud-firestore]\n",
      "   ----------------------------------- ---- 16/18 [google-cloud-firestore]\n",
      "   ----------------------------------- ---- 16/18 [google-cloud-firestore]\n",
      "   ----------------------------------- ---- 16/18 [google-cloud-firestore]\n",
      "   ----------------------------------- ---- 16/18 [google-cloud-firestore]\n",
      "   ----------------------------------- ---- 16/18 [google-cloud-firestore]\n",
      "   ------------------------------------- -- 17/18 [firebase-admin]\n",
      "   ------------------------------------- -- 17/18 [firebase-admin]\n",
      "   ------------------------------------- -- 17/18 [firebase-admin]\n",
      "   ---------------------------------------- 18/18 [firebase-admin]\n",
      "\n",
      "Successfully installed cachecontrol-0.14.4 firebase-admin-7.1.0 google-api-core-2.28.1 google-auth-2.43.0 google-cloud-core-2.5.0 google-cloud-firestore-2.21.0 google-cloud-storage-3.7.0 google-crc32c-1.7.1 google-resumable-media-2.8.0 googleapis-common-protos-1.72.0 grpcio-1.76.0 grpcio-status-1.76.0 h2-4.3.0 hpack-4.1.0 hyperframe-6.1.0 proto-plus-1.26.1 protobuf-6.33.2 rsa-4.9.1\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install firebase-admin"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "bb6e7263-65f3-4502-abb1-8e158691982e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import firebase_admin\n",
    "from firebase_admin import credentials, firestore"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "b9c3fcd6-3361-46a3-b69b-c6510e00c4a9",
   "metadata": {},
   "outputs": [],
   "source": [
    "cred = credentials.Certificate(\"dataanalyser-c7658-firebase-adminsdk-fbsvc-05e1727bfe.json\")\n",
    "firebase_admin.initialize_app(cred)\n",
    "db = firestore.client()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "3e0614f4-f3a8-4e95-b341-9fdbadfd88c2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['.anaconda',\n",
       " '.conda',\n",
       " '.condarc',\n",
       " '.continuum',\n",
       " '.idlerc',\n",
       " '.ipynb_checkpoints',\n",
       " '.ipython',\n",
       " '.jupyter',\n",
       " '.matplotlib',\n",
       " '.spyder-py3',\n",
       " '.streamlit',\n",
       " '.virtual_documents',\n",
       " '1NPDPRO5.DOC',\n",
       " '3D Objects',\n",
       " '5655',\n",
       " 'abhi .ipynb',\n",
       " 'adddd',\n",
       " 'All_in_One_Data_App',\n",
       " 'anaconda3',\n",
       " 'anaconda_projects',\n",
       " 'app.py',\n",
       " 'app2.py',\n",
       " 'AppData',\n",
       " 'Application Data',\n",
       " 'category_sales.png',\n",
       " 'Contacts',\n",
       " 'Cookies',\n",
       " 'Data Analysis',\n",
       " 'dataanalyser-c7658-firebase-adminsdk-fbsvc-05e1727bfe.json',\n",
       " 'Desktop',\n",
       " 'Documents',\n",
       " 'Downloads',\n",
       " 'ecommerce_sales_data.csv',\n",
       " 'Favorites',\n",
       " 'IntelGraphicsProfiles',\n",
       " 'Jedi',\n",
       " 'Links',\n",
       " 'Local Settings',\n",
       " 'Muse Hub',\n",
       " 'Music',\n",
       " 'My Documents',\n",
       " 'NetHood',\n",
       " 'NPProt.bkp',\n",
       " 'NPProt.exe',\n",
       " 'NTUSER.DAT',\n",
       " 'ntuser.dat.LOG1',\n",
       " 'ntuser.dat.LOG2',\n",
       " 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',\n",
       " 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',\n",
       " 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',\n",
       " 'ntuser.ini',\n",
       " 'OneDrive',\n",
       " 'Pictures',\n",
       " 'practical',\n",
       " 'PrintHood',\n",
       " 'PyCharmMiscProject',\n",
       " 'Recent',\n",
       " 'Saved Games',\n",
       " 'scikit_learn_data',\n",
       " 'Searches',\n",
       " 'SendTo',\n",
       " 'slaes_trend.png',\n",
       " 'Start Menu',\n",
       " 'Templates',\n",
       " 'Untitled.ipynb',\n",
       " 'Untitled1.ipynb',\n",
       " 'Untitled10.ipynb',\n",
       " 'Untitled11.ipynb',\n",
       " 'Untitled12.ipynb',\n",
       " 'Untitled13.ipynb',\n",
       " 'Untitled14.ipynb',\n",
       " 'Untitled15.ipynb',\n",
       " 'Untitled16.ipynb',\n",
       " 'Untitled17.ipynb',\n",
       " 'Untitled18.ipynb',\n",
       " 'Untitled19.ipynb',\n",
       " 'Untitled2.ipynb',\n",
       " 'Untitled3.ipynb',\n",
       " 'Untitled4.ipynb',\n",
       " 'Untitled5.ipynb',\n",
       " 'Untitled6.ipynb',\n",
       " 'Untitled7.ipynb',\n",
       " 'Untitled8.ipynb',\n",
       " 'Untitled9.ipynb',\n",
       " 'Videos']"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import os \n",
    "os.listdir()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a8adb407-f851-44d5-af0d-87356c62e853",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
